Repository GreysonElkins/exquisite-corpse, pull requests merged in 2020-09, with the labels that each got.

#2 Add Ertmer's PR template
  pull_request_template.md
Labels: documentation

#23 Feature/abd create header
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Header/Header.test.js
Labels: component, enhancement, styling, testing

#25 Feature/ge library
  .gitignore
  package-lock.json
  package.json
  src/ApiHelper/ApiHelper.js
  src/ApiHelper/ApiHelper.test.js
  src/assets/bookspine1.png
  src/assets/bookspine2.png
  src/assets/bookspine3.png
  src/assets/bookspine4.png
  src/assets/bookspine5.png
  src/assets/bookspine6.png
  src/assets/bookspine7.png
  src/assets/testData/testData.js
  src/components/App/App.js
  src/components/Bookshelf/Book.js
  src/components/Bookshelf/Book.test.scss
  src/components/Bookshelf/Bookshelf.js
  src/components/Bookshelf/Bookshelf.scss
  src/components/Bookshelf/Bookshelf.test.js
  src/components/LibraryView/LibraryView.js
Labels: component, enhancement, help wanted, styling

#24 Feature/nh story edit view
  src/ApiHelpers/ApiHelpers.js
  src/ApiHelpers/ApiHelpers.test.js
  src/components/App/App.js
  src/components/StoryEditFields/StoryEditFields.css
  src/components/StoryEditFields/StoryEditFields.js
  src/components/StoryEditFields/StoryEditFields.test.js
  src/components/StoryEditFooter/StoryEditFooter.css
  src/components/StoryEditFooter/StoryEditFooter.js
  src/components/StoryEditFooter/StoryEditFooter.test.js
  src/components/StoryEditView/StoryEditView.css
  src/components/StoryEditView/StoryEditView.js
  src/components/StoryEditView/StoryEditView.test.js
  src/components/Timer/Timer.test.js
  src/components/TimerDisplay/TimerDisplay.css
  src/components/TimerDisplay/TimerDisplay.js
  src/components/TimerDisplay/TimerDisplay.test.js
Labels: component, enhancement

#27 Feature/cc welcome page basics
  src/ApiHelpers/apiCalls.js
  src/assets/drawing1.png
  src/assets/drawing2.png
  src/assets/drawing3.png
  src/assets/drawing4.png
  src/assets/drawing5.png
  src/assets/drawing6.png
  src/components/App/App.js
  src/components/GameHistory/GameHistory.css
  src/components/GameHistory/GameHistory.js
  src/components/GameHistory/GameHistory.test.js
  src/components/Instructions/Instructions.css
  src/components/Instructions/Instructions.js
  src/components/Instructions/Instructions.test.js
  src/components/PromptCards/PromptCards.css
  src/components/PromptCards/PromptCards.js
  src/components/PromptCards/PromptCards.test.js
  src/components/WelcomePageView/WelcomePageView.js
  src/components/WelcomePageView/WelcomePageView.test.js
Labels: component, setup, styling, testing

#28 Feature/story display
  src/components/Bookshelf/Book.js
  src/components/Bookshelf/Book.test.js
  src/components/Bookshelf/Book.test.scss
  src/components/Bookshelf/Bookshelf.js
  src/components/Bookshelf/Bookshelf.test.js
  src/components/LibraryView/LibraryView.js
  src/components/LibraryView/LibraryView.test.js
  src/components/PublishedStory/PublishedStory.css
  src/components/PublishedStory/PublishedStory.js
  src/components/PublishedStory/PublishedStory.test.js
Labels: component, enhancement, testing

#30 Feature/abd story setup
  src/components/StorySetup/StorySetup.css
  src/components/StorySetup/StorySetup.js
  src/components/StorySetup/StorySetup.test.js
  src/components/StorySetupView/StorySetupView.css
  src/components/StorySetupView/StorySetupView.js
Labels: component, enhancement, styling, testing

#39 Feature/nh prompt display
  src/ApiHelper/ApiHelper.js
  src/ApiHelpers/ApiHelpers.js
  src/ApiHelpers/ApiHelpers.test.js
  src/ApiHelpers/apiCalls.js
  src/components/App/App.js
  src/components/PromptCards/PromptCards.js
  src/components/PublishedStoryView/PublishedStoryView.css
  src/components/PublishedStoryView/PublishedStoryView.js
  src/components/PublishedStoryView/PublishedStoryView.test.js
  src/components/StoryEditFields/StoryEditFields.js
  src/components/StoryEditFields/StoryEditFields.test.js
  src/components/StoryEditView/StoryEditView.js
  src/components/StorySetup/StorySetup.js
  src/components/StorySetupView/StorySetupView.js
  src/components/WelcomePageView/WelcomePageView.js
Labels: enhancement, question

#44 Style/abd sass transition
  src/assets/backgrounds/Secondary Background.jpg
  src/assets/backgrounds/Story_read.jpg
  src/assets/backgrounds/mainBackground.jpg
  src/components/App/App.css
  src/components/App/App.js
  src/components/App/App.scss
  src/components/GameHistory/GameHistory.js
  src/components/GameHistory/GameHistory.scss
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Header/Header.scss
  src/components/Instructions/Instructions.css
  src/components/Instructions/Instructions.js
  src/components/Instructions/Instructions.scss
  src/components/LibraryView/LibraryView.css
  src/components/PromptCards/PromptCards.js
  src/components/PromptCards/PromptCards.scss
  src/components/PublishedStory/PublishedStory.js
  src/components/PublishedStory/PublishedStory.scss
  src/components/StoryEditFields/StoryEditFields.js
  src/components/StoryEditFields/StoryEditFields.scss
  src/components/StoryEditFooter/StoryEditFooter.js
  src/components/StoryEditFooter/StoryEditFooter.scss
  src/components/StoryEditView/StoryEditView.js
  src/components/StoryEditView/StoryEditView.scss
  src/components/StorySetup/StorySetup.js
  src/components/StorySetup/StorySetup.scss
  src/components/StorySetup/StorySetup.test.js
  src/components/StorySetupView/StorySetupView.js
  src/components/StorySetupView/StorySetupView.scss
  src/components/TimerDisplay/TimerDisplay.css
  src/components/WelcomePageView/WelcomePageView.css
  src/styles/fonts.scss
Labels: styling

#47 Style/abd welcome page
  src/components/App/App.scss
  src/components/Bookshelf/Bookshelf.scss
  src/components/GameHistory/GameHistory.scss
  src/components/Header/Header.scss
  src/components/Instructions/Instructions.js
  src/components/Instructions/Instructions.scss
  src/components/WelcomePageView/WelcomePageView.js
  src/styles/fonts.scss
Labels: refactor, styling

#49 Feature/cc login
  src/ApiHelper/ApiHelper.js
  src/assets/login-paper.png
  src/components/App/App.js
  src/components/Login/Login.js
  src/components/Login/Login.scss
  src/components/StoryEditView/StoryEditView.js
Labels: component, enhancement, styling

#55 Feature/abd storytime
  src/ApiHelper/ApiHelper.js
  src/components/App/App.js
  src/components/Bookshelf/Bookshelf.scss
  src/components/Instructions/Instructions.js
  src/components/Instructions/Instructions.scss
  src/components/Login/Login.js
  src/components/StoryEditFields/StoryEditFields.js
  src/components/StoryEditFooter/StoryEditFooter.js
  src/components/StoryEditView/LiveDisplay.js
  src/components/StoryEditView/StoryEditView.js
  src/components/StorySetupView/StorySetupView.js
  src/components/WelcomePageView/WelcomePageView.js
Labels: bug, enhancement, refactor

#67 Ge bug hunt
  src/components/App/App.js
  src/components/App/App.scss
  src/components/Bookshelf/Book.js
  src/components/Bookshelf/Bookshelf.js
  src/components/GameHistory/GameHistory.js
  src/components/Header/Header.js
  src/components/Instructions/Instructions.js
  src/components/LibraryView/LibraryView.js
  src/components/Login/Login.js
  src/components/PublishedStory/PublishedStory.js
  src/components/StorySetup/StorySetup.js
  src/components/StorySetup/StorySetup.scss
  src/components/StorySetupView/StorySetupView.js
  src/components/WelcomePageView/WelcomePageView.js
Labels: bug, enhancement, refactor, styling

#69 Feature/ge user creation
  src/ApiHelper/ApiHelper.js
  src/components/App/App.js
  src/components/Login/Login.js
  src/components/Login/Login.scss
Labels: component, enhancement

#71 Style/abd storysetup
  src/components/App/App.js
  src/components/Header/Header.js
  src/components/StorySetup/StorySetup.js
  src/components/StorySetup/StorySetup.scss
  src/components/StorySetupView/StorySetupView.js
Labels: refactor, styling

#70 Nh login redirects
  src/components/App/App.js
  src/components/Bookshelf/Book.js
  src/components/WelcomePageView/WelcomePageView.js
Labels: enhancement

#73 Bug/abd storyedit route
  src/components/App/App.js
  src/components/StoryEditFooter/StoryEditFooter.js
  src/components/StoryEditView/StoryEditView.js
  src/components/StorySetup/StorySetup.scss
  src/components/StorySetupView/StorySetupView.js
Labels: bug

#75 Feature/nh user flow tweaks
  src/components/App/App.js
  src/components/Header/Header.js
  src/components/Login/Login.js
  src/components/TimerDisplay/TimerDisplay.js
Labels: enhancement

#74 Feature/ge author page
  src/ApiHelper/ApiHelper.js
  src/components/App/App.js
  src/components/Bookshelf/Book.js
  src/components/Header/Header.js
  src/components/Login/Login.scss
  src/components/UserPage/UserPage.js
  src/components/UserPage/UserPage.scss
  src/components/UserPage/UserPage.test.js
Labels: component, enhancement

#76 Readme/abd create readme
  README.md
  src/components/Header/Header.js
Labels: documentation

#77 Style/abd cleanup library
  README.md
  src/components/LibraryView/LibraryView.js
  src/components/LibraryView/LibraryView.scss
  src/components/PublishedStory/PublishedStory.js
  src/components/PublishedStory/PublishedStory.scss
Labels: styling

#80 Update readme to reflect new/live version of server
  README.md
  src/ApiHelper/ApiHelper.js
Labels: documentation
